services:
  database:
    image: postgres:16
    container_name: mandator_energy_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mandator_energy_db
      POSTGRES_USER: mandator_user
      POSTGRES_PASSWORD: mandator_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mandator-api:
    build:
      context: ./mandator-api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mandator_energy_db
      - SPRING_DATASOURCE_USERNAME=mandator_user
      - SPRING_DATASOURCE_PASSWORD=mandator_pass
  
  producer1:
    build: ./producer
    env_file:
      - .env
    environment:
      - PORT=5001
      - WEATHER_CITY=Vienna
      - SOLAR_MULTIPLIER=1.0
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  producer2:
    build: ./producer
    env_file:
      - .env
    environment:
      - PORT=5002
      - WEATHER_CITY=Vienna
      - SOLAR_MULTIPLIER=1.0
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq

  producer3:
    build: ./producer
    env_file:
      - .env
    environment:
      - PORT=5003
      - WEATHER_CITY=Vienna
      - SOLAR_MULTIPLIER=1.0
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq

  # Use multiple users
  user1:
    build: ./user
    environment:
      - PORT=5004
      - SOLAR_MULTIPLIER=1
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq

  user2:
    build: ./user
    environment:
      - PORT=5005
      - SOLAR_MULTIPLIER=3
    ports:
      - "5005:5005"
    depends_on:
      - rabbitmq

  user3:
    build: ./user
    environment:
      - PORT=5006
      - SOLAR_MULTIPLIER=3
    ports:
      - "5006:5006"
    depends_on:
      - rabbitmq

  usage-service:
    build:
      context: ./usage-service
      dockerfile: Dockerfile
    environment:
      - PORT=5004
      - SOLAR_MULTIPLIER=1.0
      - DB_NAME=mandator_energy_db
      - DB_USER=mandator_user
      - DB_PASSWORD=mandator_pass
      - DB_HOST=database
    depends_on:
      - database
      - rabbitmq
    ports:
      - "5007:5007"

  percentage-service:
    build:
      context: ./percentage-service
      dockerfile: Dockerfile
    environment:
    - DB_NAME=mandator_energy_db
    - DB_USER=mandator_user
    - DB_PASSWORD=mandator_pass
    - DB_HOST=database
    depends_on:
      - database
      - rabbitmq
    ports:
      - "5008:5008"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata: