services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=disysuser
      - POSTGRES_PASSWORD=disyspw
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  # Use multiple producers
  # SOLAR_MULTIPLIER is used to simulate different solar production rates
  # environment port is for flask to know what it should use for each service
  producer1:
    build: ./producer
    environment:
      - PORT=5001
      - SOLAR_MULTIPLIER=1.1
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
    volumes:
      - ./util:/app/util  

  producer2:
    build: ./producer
    environment:
      - PORT=5002
      - SOLAR_MULTIPLIER=1.2
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
    volumes:
      - ./util:/app/util      

  producer3:
    build: ./producer
    environment:
      - PORT=5003
      - SOLAR_MULTIPLIER=1.0 
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    volumes:
      - ./util:/app/util        

  # Use multiple users
  user1:
    build: ./user
    environment:
      - PORT=5004
      - SOLAR_MULTIPLIER=1.1 
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq
    volumes:
      - ./util:/app/util

  user2:
    build: ./user
    environment:
      - PORT=5005
      - SOLAR_MULTIPLIER=1.3 
    ports:
      - "5005:5005"
    depends_on:
      - rabbitmq
    volumes:
      - ./util:/app/util     

  user3:
    build: ./user
    environment:
      - PORT=5006
      - SOLAR_MULTIPLIER=1.0 
    ports:
      - "5006:5006"
    depends_on:
      - rabbitmq
    volumes:
      - ./util:/app/util    


  usage-service:
    build:
      context: ./usage-service
      dockerfile: Dockerfile
    env_file:
      - .env  
    volumes:
      - ./util:/app/util
    depends_on:
      - database
      - rabbitmq
    ports:
      - "5007:5007"

  percentage-service:
    build:
      context: ./percentage-service
      dockerfile: Dockerfile
    env_file:
      - .env  
    volumes:
      - ./util:/app/util
    depends_on:
      - database
      - rabbitmq
    ports:
      - "5008:5008"

  mandator-api:
    build:
      context: ./mandator-api
    ports:
      - "8081:8080" #8081 is the port on the host machine, 8080 is the port in the container
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mandator_energy_db
      - SPRING_DATASOURCE_USERNAME=disysuser
      - SPRING_DATASOURCE_PASSWORD=disyspw
